config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resource :student, only: [:new, :create] do
    collection do
      post :call_on
    end
  end

end

app/models/student.rb
class Student < ActiveRecord::Base

  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash.notice = "#{@student.name} has been saved"
      redirect_to root_path
    else
      flash.now[:alert] = "Student could not be added"
      render :new
    end
  end

  def call_on
    @random_student = Student.all.sample
    @random_student.updated_at = DateTime.now
    @random_student.save
  end

  protected

  def student_params
    params.require(:student).permit(:name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @students = Student.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "StudentSelect"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    <script type="text/javascript" src="//use.typekit.net/ayn0ftv.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  %body
    %main
      - if notice.present?
        .alert-box.success{ "data-alert" => "" }
          = notice
          %a.close{ href: "#" } &times;
      - if alert.present?
        .alert-box.alert{ "data-alert" => "" }
          = alert
          %a.close{ href: "#" } &times;
      = yield

    = javascript_include_tag "application"
    = javascript_tag '$.fx.off = true;' if Rails.env.test?

app/views/students/_student.html.haml
%li= "#{student.name}, #{time_ago_in_words(student.updated_at)} ago"

app/views/students/call_on.html.haml
%h2 The chosen one:
%h1= @random_student.name
=link_to "Go Back", root_path

app/views/students/new.html.haml
= simple_form_for @student, url: student_path do |f|
  = f.input :name
  = f.submit "Submit"

app/views/welcome/index.html.haml
%h1 Welcome to StudentSelect!

=button_to "Pick Someone", call_on_student_path, class: "button"
%h2 Students:
%ul= render @students

=link_to "Add Student", new_student_path, class: "button"